default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: curiosity_development

test:
  <<: *default
  database: curiosity_test

production:
  <<: *default
  database: curiosity_production
  username: curiosity
  password: <%= ENV['CURIOSITY_DATABASE_PASSWORD'] %>